name: Go-JSON-Parser

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        path_to_write_report: ./coverage.txt
        verbose: true # optional (default = false)

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run golangci-lint with reviewdog
      uses: reviewdog/action-golangci-lint@v1.24.0

